<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.atur256.graalvm-webimage-interop</groupId>
    <artifactId>graalvm-webimage-interop</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>

    <name>graalvm-webimage-interop</name>
    <description>Java wrappers for JavaScript global objects with GraalVM WebImage interop</description>
    <url>https://github.com/Atur256/graalvm-webimage-interop</url>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>atur256</id>
            <name>Arthur Schwaiger</name>
            <email>-</email>
            <url>https://github.com/atur256</url>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/Atur256/graalvm-webimage-interop.git</connection>
        <developerConnection>scm:git:https://github.com/Atur256/graalvm-webimage-interop.git</developerConnection>
        <url>https://github.com/Atur256/graalvm-webimage-interop</url>
    </scm>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <graalvm.version>25.3.0</graalvm.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>6.1.0-M1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Compiler plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <!--                    <excludes>-->
                    <!--                        <excludes>**/tests/**</excludes>-->
                    <!--                    </excludes>-->
                </configuration>
            </plugin>

            <!-- Source JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Javadoc JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- GPG signing -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!-- Profiles -->
    <profiles>
        <!-- Profile for normal JAR build without tests -->
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <!-- Exclude test sources from compilation in the main build -->
                            <excludes>
                                <exclude>**/tests/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Profile for building only test package via GraalVM -->
        <profile>
            <id>test-native</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <!-- Rename, to clarify that this version includes the code for the tests -->
                <finalName>${project.artifactId}-native-tests</finalName>
                <plugins>
                    <!-- Maven Antrun plugin to create JS directory -->
                    <plugin>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>mkdir-js-dir</id>
                                <phase>generate-sources</phase>
                                <configuration>
                                    <target>
                                        <mkdir dir="${project.build.directory}/native-tests"/>
                                    </target>
                                </configuration>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- GraalVM native plugin for test package -->
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.11.3</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native-tests</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>io.github.atur256.graalvmwebimageinterop.tests.TestRunner</mainClass>
                            <buildArgs>
                                <option>--tool:svm-wasm</option>
                                <option>-Dcom.oracle.graalvm.iswebimage=true</option>
                                <option>-H:+UnlockExperimentalVMOptions</option>
                                <option>-o</option>
                                <option>${project.build.directory}/native-tests/tests</option>
                                <option>-H:-ClosureCompiler</option>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <distributionManagement>
        <repository>
            <id>ossrh</id>
            <name>OSSRH Repository</name>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
        <snapshotRepository>
            <id>ossrh-snapshots</id>
            <name>OSSRH Snapshot Repository</name>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>