name: Build & Test (GraalVM + Node)

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache GraalVM
      - name: Cache GraalVM
        id: graalvm-cache
        uses: actions/cache@v3
        with:
          path: /opt/graalvm-jdk-25e1-25.0.1-ea.06
          key: graalvm-25e1-${{ runner.os }}-v1

      # Download GraalVM
      - name: Download Oracle GraalVM 25e1 EA
        if: steps.graalvm-cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o graalvm.tar.gz \
            https://github.com/graalvm/oracle-graalvm-ea-builds/releases/download/jdk-25e1-25.0.1-ea.06/graalvm-jdk-25e1-25.0.1-ea.06_linux-x64_bin.tar.gz
          sudo tar -xzf graalvm.tar.gz -C /opt

      # Set GraalVM environment
      - name: Set GraalVM environment
        run: |
          EXTRACTED_DIR=$(tar -tzf graalvm.tar.gz | head -1 | cut -f1 -d"/")
          echo "GRAALVM_HOME=/opt/$EXTRACTED_DIR" >> $GITHUB_ENV
          echo "JAVA_HOME=/opt/$EXTRACTED_DIR" >> $GITHUB_ENV
          echo "/opt/$EXTRACTED_DIR/bin" >> $GITHUB_PATH

      # Verify GraalVM
      - name: Verify GraalVM
        run: |
          java --version
          native-image --version

      # Build & native tests
      - name: Build with Maven
        run: mvn clean package -e -Ptest-native

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'

      # Run Node tests
      - name: Run generated Node.js tests
        run: node target/native-tests/tests.js
