name: Build & Test (GraalVM + Node)

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

     # Setup GraalVM with caching
      - name: Setup Oracle GraalVM EA
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25e1-ea'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: true

      # Set GraalVM environment
      - name: Set GraalVM environment
        run: |
          EXTRACTED_DIR=$(tar -tzf graalvm.tar.gz | head -1 | cut -f1 -d"/")
          echo "GRAALVM_HOME=/opt/$EXTRACTED_DIR" >> $GITHUB_ENV
          echo "JAVA_HOME=/opt/$EXTRACTED_DIR" >> $GITHUB_ENV
          echo "/opt/$EXTRACTED_DIR/bin" >> $GITHUB_PATH

      # Verify GraalVM installation
      - name: Verify GraalVM
        run: |
          java --version
          native-image --version

      # Build with Maven (native image tests)
      - name: Build with Maven
        run: mvn clean package -Ptest-native

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'

      # Run Node tests
      - name: Run generated Node.js tests
        run: node target/native-tests/tests.js
